Modify README

diff --git a/scripts/publish b/scripts/publish
--- a/scripts/publish
+++ b/scripts/publish
@@ -15,17 +15,17 @@ scripts/clean
 #     exit 1
 # fi
 
-if ! pip show wheel &>/dev/null ; then
-    echo "Unable to find the 'wheel' command."
-    echo "Install from PyPI, using 'pip install wheel'."
-    exit 1
-fi
+# if ! pip show wheel &>/dev/null ; then
+#     echo "Unable to find the 'wheel' command."
+#     echo "Install from PyPI, using 'pip install wheel'."
+#     exit 1
+# fi
 
-if ! command -v "$mkdocs" &>/dev/null ; then
-    echo "Unable to find the 'mkdocs' command."
-    echo "Install from PyPI, using pip install mkdocs'."
-    exit 1
-fi
+# if ! command -v "$mkdocs" &>/dev/null ; then
+#     echo "Unable to find the 'mkdocs' command."
+#     echo "Install from PyPI, using pip install mkdocs'."
+#     exit 1
+# fi
 
 find ${PACKAGE} -type f -name "*.py[co]" -delete
 find ${PACKAGE} -type d -name __pycache__ -delete
